# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main.ui'
#
# Created: Tue Sep 16 12:40:40 2014
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(402, 391)
        self.central_widget = QtWidgets.QWidget(main_window)
        self.central_widget.setObjectName("central_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.central_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.form_layout = QtWidgets.QFormLayout()
        self.form_layout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.form_layout.setObjectName("form_layout")
        self.label = QtWidgets.QLabel(self.central_widget)
        self.label.setObjectName("label")
        self.form_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.serial_spinbox = QtWidgets.QSpinBox(self.central_widget)
        self.serial_spinbox.setSuffix("")
        self.serial_spinbox.setPrefix("")
        self.serial_spinbox.setMaximum(1000000)
        self.serial_spinbox.setObjectName("serial_spinbox")
        self.form_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.serial_spinbox)
        self.all_selected = QtWidgets.QCheckBox(self.central_widget)
        self.all_selected.setObjectName("all_selected")
        self.form_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.all_selected)
        self.bootstrap_selected = QtWidgets.QCheckBox(self.central_widget)
        self.bootstrap_selected.setObjectName("bootstrap_selected")
        self.form_layout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.bootstrap_selected)
        self.bootstrap_button = QtWidgets.QPushButton(self.central_widget)
        self.bootstrap_button.setFlat(True)
        self.bootstrap_button.setObjectName("bootstrap_button")
        self.form_layout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.bootstrap_button)
        self.uboot_selected = QtWidgets.QCheckBox(self.central_widget)
        self.uboot_selected.setObjectName("uboot_selected")
        self.form_layout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.uboot_selected)
        self.uboot_button = QtWidgets.QPushButton(self.central_widget)
        self.uboot_button.setFlat(True)
        self.uboot_button.setObjectName("uboot_button")
        self.form_layout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.uboot_button)
        self.ubootenv_selected = QtWidgets.QCheckBox(self.central_widget)
        self.ubootenv_selected.setObjectName("ubootenv_selected")
        self.form_layout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.ubootenv_selected)
        self.ubootenv_button = QtWidgets.QPushButton(self.central_widget)
        self.ubootenv_button.setFlat(True)
        self.ubootenv_button.setObjectName("ubootenv_button")
        self.form_layout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.ubootenv_button)
        self.kernel_selected = QtWidgets.QCheckBox(self.central_widget)
        self.kernel_selected.setObjectName("kernel_selected")
        self.form_layout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.kernel_selected)
        self.kernel_button = QtWidgets.QPushButton(self.central_widget)
        self.kernel_button.setFlat(True)
        self.kernel_button.setObjectName("kernel_button")
        self.form_layout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.kernel_button)
        self.rootfs_selected = QtWidgets.QCheckBox(self.central_widget)
        self.rootfs_selected.setObjectName("rootfs_selected")
        self.form_layout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.rootfs_selected)
        self.rootfs_button = QtWidgets.QPushButton(self.central_widget)
        self.rootfs_button.setFlat(True)
        self.rootfs_button.setObjectName("rootfs_button")
        self.form_layout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.rootfs_button)
        self.userdata_selected = QtWidgets.QCheckBox(self.central_widget)
        self.userdata_selected.setObjectName("userdata_selected")
        self.form_layout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.userdata_selected)
        self.userdata_button = QtWidgets.QPushButton(self.central_widget)
        self.userdata_button.setFlat(True)
        self.userdata_button.setObjectName("userdata_button")
        self.form_layout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.userdata_button)
        self.verticalLayout.addLayout(self.form_layout)
        spacerItem = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontal_layout = QtWidgets.QHBoxLayout()
        self.horizontal_layout.setObjectName("horizontal_layout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontal_layout.addItem(spacerItem1)
        self.flash_button = QtWidgets.QPushButton(self.central_widget)
        self.flash_button.setObjectName("flash_button")
        self.horizontal_layout.addWidget(self.flash_button)
        self.verticalLayout.addLayout(self.horizontal_layout)
        main_window.setCentralWidget(self.central_widget)
        self.menubar = QtWidgets.QMenuBar(main_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 402, 25))
        self.menubar.setObjectName("menubar")
        self.menu_file = QtWidgets.QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        main_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)
        self.action_open = QtWidgets.QAction(main_window)
        self.action_open.setObjectName("action_open")
        self.action_exit = QtWidgets.QAction(main_window)
        self.action_exit.setObjectName("action_exit")
        self.action_save = QtWidgets.QAction(main_window)
        self.action_save.setObjectName("action_save")
        self.action_save_as = QtWidgets.QAction(main_window)
        self.action_save_as.setObjectName("action_save_as")
        self.menu_file.addAction(self.action_open)
        self.menu_file.addAction(self.action_save)
        self.menu_file.addAction(self.action_save_as)
        self.menu_file.addAction(self.action_exit)
        self.menubar.addAction(self.menu_file.menuAction())

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "MainWindow"))
        self.label.setText(_translate("main_window", "serial"))
        self.all_selected.setText(_translate("main_window", "All"))
        self.bootstrap_selected.setText(_translate("main_window", "bootstrap"))
        self.bootstrap_button.setText(_translate("main_window", "None Selected"))
        self.uboot_selected.setText(_translate("main_window", "uboot"))
        self.uboot_button.setText(_translate("main_window", "None Selected"))
        self.ubootenv_selected.setText(_translate("main_window", "uboot env"))
        self.ubootenv_button.setText(_translate("main_window", "None Selected"))
        self.kernel_selected.setText(_translate("main_window", "kernel"))
        self.kernel_button.setText(_translate("main_window", "None Selected"))
        self.rootfs_selected.setText(_translate("main_window", "rootfs"))
        self.rootfs_button.setText(_translate("main_window", "None Selected"))
        self.userdata_selected.setText(_translate("main_window", "userdata"))
        self.userdata_button.setText(_translate("main_window", "None Selected"))
        self.flash_button.setText(_translate("main_window", "Flash"))
        self.menu_file.setTitle(_translate("main_window", "File"))
        self.action_open.setText(_translate("main_window", "&Open Config"))
        self.action_open.setShortcut(_translate("main_window", "Ctrl+O"))
        self.action_exit.setText(_translate("main_window", "E&xit"))
        self.action_exit.setShortcut(_translate("main_window", "Ctrl+X"))
        self.action_save.setText(_translate("main_window", "&Save Config"))
        self.action_save.setShortcut(_translate("main_window", "Ctrl+S"))
        self.action_save_as.setText(_translate("main_window", "Save &As"))
        self.action_save_as.setShortcut(_translate("main_window", "Ctrl+A"))

